In [0]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[7.3901e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6852, 0.4196, 0.0109],
        [0.9299, 0.8073, 0.6020],
        [0.0522, 0.6472, 0.3135],
        [0.9001, 0.5520, 0.6207],
        [0.8986, 0.7878, 0.3018]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0741, -0.0750, -2.0314],
        [ 0.3960, -1.1057,  0.0280],
        [ 0.8189,  2.2386, -1.9393],
        [ 0.1506, -0.1715, -0.6023],
        [ 0.9103, -0.1477,  1.0540]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
print(type(x.size()))

<class 'torch.Size'>


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9144,  0.8175, -1.0789],
        [ 0.9654, -0.8531,  0.3573],
        [ 0.9899,  2.3017, -1.4374],
        [ 0.5595,  0.8247,  0.2157],
        [ 1.5231,  0.0899,  1.6966]])


In [10]:
print(torch.add(x, y))

tensor([[-0.9144,  0.8175, -1.0789],
        [ 0.9654, -0.8531,  0.3573],
        [ 0.9899,  2.3017, -1.4374],
        [ 0.5595,  0.8247,  0.2157],
        [ 1.5231,  0.0899,  1.6966]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9144,  0.8175, -1.0789],
        [ 0.9654, -0.8531,  0.3573],
        [ 0.9899,  2.3017, -1.4374],
        [ 0.5595,  0.8247,  0.2157],
        [ 1.5231,  0.0899,  1.6966]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.9144,  0.8175, -1.0789],
        [ 0.9654, -0.8531,  0.3573],
        [ 0.9899,  2.3017, -1.4374],
        [ 0.5595,  0.8247,  0.2157],
        [ 1.5231,  0.0899,  1.6966]])


In [13]:
print(x[:, 1])

tensor([-0.0750, -1.1057,  2.2386, -0.1715, -0.1477])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = x.view(-1, 8)
print(x)

tensor([[-0.5097,  0.7485,  1.2069, -0.5802,  0.6972, -0.5005, -1.2221, -1.1981],
        [ 0.0899, -0.6642,  1.5871, -1.4189, -0.7676, -0.9783, -0.8842, -1.0565]])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1483])
-0.1483096182346344


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [21]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
# Tensors can be moved onto any device using the .to method.
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x, device=device)
    
    x = x.to(device)
    
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.8517], device='cuda:0')
tensor([0.8517], dtype=torch.float64)
