In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [5]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
A.shape

(3, 2)

In [7]:
x.shape

(4,)

In [8]:
len(x)

4

In [10]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
A_t.shape

(2, 3)