In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [4]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [6]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [9]:
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

In [10]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [11]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [12]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

In [13]:
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

In [14]:
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

In [15]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [17]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

In [18]:
D = (A.dot(B)).dot(C)
D

array([[100],
       [ 85],
       [287]])

In [19]:
# AB != BA
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [20]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [21]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

In [22]:
BA = np.dot(B, A)
BA

array([[28, 30],
       [16, 16]])

In [24]:
# (AB)' = B'A'
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [25]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [26]:
AB_t = A.dot(B).T
AB_t

array([[16, 13, 47],
       [12, 11, 33]])

In [27]:
BtAt = np.dot(B.T, A.T)
BtAt

array([[16, 13, 47],
       [12, 11, 33]])