In [1]:
from __future__ import absolute_import, division, print_function
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

In [0]:
layer = tf.keras.layers.Dense(100)

# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [5]:
# To use a layer, simply call it
layer(tf.zeros([10, 5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.49379045, -0.3665372 ,  0.14554471, -0.46766472, -0.15507126,
         -0.4959885 ,  0.35320008,  0.14378184, -0.19567034, -0.23598865],
        [-0.01036763,  0.3831584 , -0.5841353 ,  0.23726445,  0.21549547,
          0.22180736,  0.01242274, -0.3791317 ,  0.41561788, -0.07272905],
        [ 0.08726472, -0.1241765 , -0.60982674,  0.09299845, -0.3688408 ,
         -0.56472105,  0.24621367, -0.12378144,  0.17881197, -0.4757105 ],
        [ 0.6283614 ,  0.31576997, -0.07498908,  0.08822942, -0.19261217,
          0.44172972,  0.0987342 ,  0.02391618,  0.5630161 , -0.34190127],
        [-0.56515634, -0.27314067,  0.32780534,  0.5403902 ,  0.03403902,
          0.5479397 , -0.390353  ,  0.22201502,  0.5826315 ,  0.42326826]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [8]:
layer.kernel

<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.49379045, -0.3665372 ,  0.14554471, -0.46766472, -0.15507126,
        -0.4959885 ,  0.35320008,  0.14378184, -0.19567034, -0.23598865],
       [-0.01036763,  0.3831584 , -0.5841353 ,  0.23726445,  0.21549547,
         0.22180736,  0.01242274, -0.3791317 ,  0.41561788, -0.07272905],
       [ 0.08726472, -0.1241765 , -0.60982674,  0.09299845, -0.3688408 ,
        -0.56472105,  0.24621367, -0.12378144,  0.17881197, -0.4757105 ],
       [ 0.6283614 ,  0.31576997, -0.07498908,  0.08822942, -0.19261217,
         0.44172972,  0.0987342 ,  0.02391618,  0.5630161 , -0.34190127],
       [-0.56515634, -0.27314067,  0.32780534,  0.5403902 ,  0.03403902,
         0.5479397 , -0.390353  ,  0.22201502,  0.5826315 ,  0.42326826]],
      dtype=float32)>

In [9]:
layer.bias

<tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [10]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.49379045, -0.3665372 ,  0.14554471, -0.46766472, -0.15507126,
         -0.4959885 ,  0.35320008,  0.14378184, -0.19567034, -0.23598865],
        [-0.01036763,  0.3831584 , -0.5841353 ,  0.23726445,  0.21549547,
          0.22180736,  0.01242274, -0.3791317 ,  0.41561788, -0.07272905],
        [ 0.08726472, -0.1241765 , -0.60982674,  0.09299845, -0.3688408 ,
         -0.56472105,  0.24621367, -0.12378144,  0.17881197, -0.4757105 ],
        [ 0.6283614 ,  0.31576997, -0.07498908,  0.08822942, -0.19261217,
          0.44172972,  0.0987342 ,  0.02391618,  0.5630161 , -0.34190127],
        [-0.56515634, -0.27314067,  0.32780534,  0.5403902 ,  0.03403902,
          0.5479397 , -0.390353  ,  0.22201502,  0.5826315 ,  0.42326826]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [0]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    print(input_shape)
    self.kernel = self.add_weight("kernel",
                                    shape=[int(input_shape[-1]),
                                           self.num_outputs])

  def call(self, input):
    return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)

In [30]:
_ = layer(tf.zeros([10, 5]))

(10, 5)


In [31]:
print([weight.name for weight in layer.trainable_variables])

['my_dense_layer_7/kernel:0']


In [32]:
layer.trainable_variables # <> 이게 하나야.

[<tf.Variable 'my_dense_layer_7/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.45816833, -0.49171165,  0.6013687 ,  0.34734476,  0.07231909,
          0.44895524,  0.07474512, -0.50821114,  0.5397443 ,  0.53489405],
        [ 0.15428579,  0.15059191, -0.10210824,  0.09221131,  0.2057432 ,
         -0.03687757, -0.27937293,  0.5959242 , -0.51461697, -0.30716276],
        [-0.44525516,  0.59981996, -0.27793893, -0.31800467, -0.45147222,
          0.5317454 , -0.22431016, -0.411229  , -0.26303342,  0.3749525 ],
        [-0.50594884, -0.50468916,  0.10604036, -0.54737866,  0.40290183,
          0.04312116, -0.500249  , -0.62494427, -0.56236345, -0.55961263],
        [-0.44749832,  0.12046182,  0.4747513 , -0.40454692,  0.37135917,
         -0.28050417, -0.17471862, -0.26096022,  0.19712967, -0.00817144]],
       dtype=float32)>]

In [0]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    # Initialize input-independent
    # Model handle layer
    super(ResnetIdentityBlock, self).__init__(name='')
    filter1, filter2, filter3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filter1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filter2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filter3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()
  
  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)

In [0]:
block = ResnetIdentityBlock(1, [1, 2, 3])

In [38]:
block.layers
# Model traks not only variables, internal layers.

In [0]:
# 한번 호출하면 차원이 정해지는 것 같음.
# build가 자동으로 호출하나봐.
_ = block(tf.zeros([1, 2, 3, 3]))

In [41]:
block.summary()

Model: "resnet_identity_block_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  4         
_________________________________________________________________
batch_normalization (BatchNo multiple                  4         
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_1 (Batch multiple                  8         
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_2 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
______________________________________________

In [42]:
# 다른 차원 호출 불가
_ = block(tf.zeros([[1, 2, 3, 3], [1, 2, 3, 3]]))

InvalidArgumentError: ignored

In [0]:
# compose many layer simply call one layer afther the other
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(2, 1, padding='same'),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(3, (1, 1)),
                              tf.keras.layers.BatchNormalization()])
# ValueError: This model has not yet been built. 
# Build the model first by calling `build()` 
# or calling `fit()` with some data, or specify an `input_shape` argument 
# in the first layer(s) for automatic build.

In [44]:
my_seq.summary()

ValueError: ignored

In [45]:
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=560, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [46]:
my_seq.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_3 (Batch multiple                  4         
_________________________________________________________________
conv2d_4 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_4 (Batch multiple                  8         
_________________________________________________________________
conv2d_5 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_5 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
___________________________________________________________