In [0]:
from __future__ import absolute_import, division, print_function

!pip install -q tensorflow-gpu==2.0.0-beta1

In [0]:
import tensorflow as tf

In [3]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [4]:
# tf.Tensor has a shape and a datatype
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np

ndarray = np.ones([3, 3])
print('TensorFlow operations convert numpy arrays to Tensors automatically')
tensor = tf.multiply(ndarray, 42)
print(tensor)

print('And Numpy operations convert Tensors to numpy arrays automatically')
print(np.add(tensor, 1))

print('The .numpy() method explicitly converts a Tensor to a numpy array')
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And Numpy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [6]:
## GPU acceleration
x = tf.random.uniform([3, 3])

print('Is there a GPU available: ')
print(tf.test.is_gpu_available())

print('Is the Tensor on GPU #0: ')
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
True
Is the Tensor on GPU #0: 
True


In [7]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
    result = time.time() - start
    
    print('10 loops: {:0.2f}ms'.format(1000 * result))
    
# Force execution on CPU
print('On CPU:')
with tf.device('CPU:0'):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith('CPU:0')
    time_matmul(x)
    
# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
    print('On GPU:')
    with tf.device('GPU:0'):
        x = tf.random.uniform([1000, 1000])
        assert x.device.endswith('GPU:0')
        time_matmul(x)

On CPU:
10 loops: 315.67ms
On GPU:
10 loops: 367.13ms


In [0]:
# tf.data.Dataset API to build a pipeline for feeding data to your model.

# Create a source Dataset using factory function like
# Dataset.from_tensors, Dataset.from_tensor_slices
# or using objects TextLineDataset, TFRecordDataset

ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write('''Line1
    Line2
    Line3
    ''')

ds_file = tf.data.TextLineDataset(filename)

In [0]:
# Apply transformations
# Use transformations like map, batch, shuffle to apply
# transofrmations to dataset records

ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file= ds_file.batch(2)

In [14]:
# tf.data.Dataset support iteration to loop over records
print('Elements of ds_tensors')
for x in ds_tensors:
    print(x)

print('\nElements in ds_file:')
for x in ds_file:
    print(x)

Elements of ds_tensors
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16  4], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line1' b'    Line2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line3' b'    '], shape=(2,), dtype=string)
